version: "3.3"
services:

    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - "./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
            - "db-data:/var/lib/mysql"
        ports:
            - "33060:33060"
        networks:
            - backend
    
    adminer:
        image: adminer:4.7
        restart: always
        ports:
            - "8080:8080"
        networks:
            - backend

networks:
    backend:

volumes:
    db-data:
