version: "3.3"
services:

    app:
        build:
            context: ./app
        restart: always
        volumes:
            - "./app:/var/www/app"
        networks:
            - backend

    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - "./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
            - "db-data:/var/lib/mysql"
        ports:
            - "33060:33060"
        networks:
            - backend
        depends_on:
            - app
    
    adminer:
        image: adminer:4.7
        restart: always
        ports:
            - "8080:8080"
        networks:
            - backend
        depends_on:
            - db

    nginx:
        build:
            context: ./nginx
        restart: always
        ports:
            - "8000:80"
        networks:
            - backend
        depends_on:
            - app

networks:
    backend:

volumes:
    db-data:
